### ISSUE TITLE
Notes fiche jeux cassés

### ISSUE THREAD

**Issue by cyril1983** [Jedisjeux/Jedisjeux#56]
| Q                 | A
| ----------------- | -----
| Bug report?       | yes
| Feature request?  | no
| Jedisjeux version | PRD

Les notes sur les fiches de jeux ne semblent plus se mettre a jour quand on rentre une note :  http://www.jedisjeux.net/jeu-de-societe/profiler

**Comment by loic425** [comment]
Je ne rencontre pas le problème sur d'autres jeux. As-tu le soucis avec d'autres jeux ??
Sinon je vais récupérer une sauvegarde de la base de prod pour essayer (je n'ai pas joué à ce jeu, ce serait bizarre d'y mettre une note).

**Comment by cyril1983** [comment]
a priori si je change/mets une note la note saffiche enfin (en haut de la fiche sous le titre du jeu) apres un refresh de la page
mais par exemple sur : 
http://www.jedisjeux.net/jeu-de-societe/burgle-bros
ya bien ma note mais pas la note globale affichée en haut ss le titre et donc dans la liste de noel (cest dommage)

**Comment by cyril1983** [comment]
a priori le bug a du etre a une epoque car maintenant ca marche mais du coup il faudrait pouvoir forcer le recalcul de la note global a partir des notes des gens pour tous les jeux pour eviter davoir a le faire à la main fiche par fiche

**Comment by loic425** [comment]
C'est ce que l'on avait évoqué ensemble sur le trello.

**Comment by loic425** [comment]
Pour le refresh, effectivement ce serait un plus de rafraîchir directement la moyenne sans avoir à recharger la page.

**Comment by cyril1983** [comment]
ok nickel du coup si tu créé aussi un tiecket pour le refresh de toutes les notes existantes on est bon et on peut fermer ce ticket
